routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('en', function () {
    \Illuminate\Support\Facades\Session::put('language', 'en');

    return back();
});
Route::get('es', function () {
    \Illuminate\Support\Facades\Session::put('language', 'es');

    return back();
});

Route::auth();

Route::get('', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::resource('ad-banners', 'AdBannersController');

Route::resource('adfiles', 'AdfilesController');

Route::resource('adpages', 'AdpagesController');

Route::get('ads/all', 'AdsController@all');
Route::get('ads/banners/{ad}', 'AdsController@banners');
Route::get('ads/subscriber-specials-email/{id}', 'AdsController@email');
Route::get('ads/email/{id}', 'AdsController@ad_email');
Route::get('ads/emailing/{id}', 'AdsController@emailing');
Route::get('ads/text/{id}', 'AdsController@ad_text');
Route::get('ads/current/{brand}', 'AdsController@current');
Route::get('ads/current_api/{brand}', 'AdsController@current_api');
Route::get('ads/duplicate/{id}', 'AdsController@duplicate');
Route::get('ads/generate-pdf/{id}', 'AdsController@generate_pdf');
Route::get('ads/export/{id}', 'AdsController@export');
Route::get('ads/export_csv/{id}', 'AdsController@export_csv');
Route::get('ads/export_csv/{id}', 'AdsController@export_csv');
Route::get('ads/mailing/{id}', 'AdsController@mailing');
Route::get('ads/pages/{brand}', 'AdsController@pages');
Route::get('ads/pdf/{id}', 'AdsController@pdf');
Route::get('ads/pdf-template/{id}', 'AdsController@pdf_template');
Route::get('ads/pdfshift/{id}', 'AdsController@pdfshift');
Route::get('ads/ad/{id}', 'AdsController@ad');
Route::get('generate-pdf/ad/{id}', 'AdsController@ad')->name('generate-pdf');
Route::post('ads/custom-report/{id}', 'AdsController@custom_report');
Route::get('ads/poster/{id}/{page}', 'AdsController@poster');
Route::get('ads/poster-pdf/{id}/{page}', 'AdsController@poster_pdf');
Route::resource('ads', 'AdsController');

Route::get('articles/{id}/delete', 'ArticlesController@delete');
Route::resource('/articles', 'ArticlesController');

Route::resource('article-category', 'ArticlesCategoriesController');

Route::resource('awg-price', 'AwgPriceController');

Route::resource('bab-feedback', 'BABFeedbackController');

Route::get('brand/stores/{id}', 'BrandsController@brand_stores');
Route::get('brand/{id}', 'BrandsController@email');
Route::resource('brands', 'BrandsController');

Route::get('campaigns/orders', 'CampaignsController@orders');
Route::get('campaigns/order-details/{id}', 'CampaignsController@order_details');
Route::get('campaigns/replicate/{id}', 'CampaignsController@replicate');
Route::resource('campaigns', 'CampaignsController');

Route::post('campaign-categories/sort', 'CampaignCategoriesController@sort');
Route::resource('campaign-categories', 'CampaignCategoriesController');

Route::resource('campaign-faqs', 'CampaignFaqsController');

Route::get('campaign-items/duplicate/{id}', 'CampaignItemsController@duplicate');
Route::resource('campaign-items', 'CampaignItemsController');

Route::resource('campaign-item-sizes', 'CampaignItemSizesController');

Route::resource('cashiers', 'CashiersController');

Route::resource('cashiersnumbers', 'CashierNumbersController');
Route::post('cashiersnumbers/{id}', 'CashierNumbersController@store');

Route::resource('categories', 'CategoriesController');

Route::resource('choices', 'ChoicesController');

Route::resource('ctw-area', 'CtwAreaController');

Route::get('ctw-evaluation/heatmap', 'CtwEvaluationController@heatmap')->name('ctw-evaluation.heatmap');
Route::resource('ctw-evaluation', 'CtwEvaluationController');
Route::post('ctw-evaluation/mark-as-completed/{id}', 'CtwEvaluationController@mark_as_completed')->name('ctw-evaluation.mark-as-completed');

Route::resource('ctw-topic', 'CtwTopicController');
Route::post('ctw-topic/store/{id}', 'CtwTopicController@store')->name('ctw-topic.store');

Route::resource('ctw-score', 'CtwScoreController');
Route::get('ctw-score/check/{evaluation}/{topic}', 'CtwScoreController@check');

Route::get('deli-ads/delete/{id}', 'DeliAdsController@destroy');
Route::get('deli-ads/up/{id}', 'DeliAdsController@up');
Route::get('deli-ads/down/{id}', 'DeliAdsController@down');
Route::resource('deli-ads', 'DeliAdsController');

Route::resource('deliMenu', 'DeliMenuController');

Route::resource('deliMenuCategory', 'DeliMenuCategoryController');
Route::get('deliMenuCategory-menu-categories/{menu_id}', 'DeliMenuCategoryController@menu_categories');

Route::resource('deliMenuItem', 'DeliMenuItemController');

Route::resource('departments', 'DepartmentsController');

Route::resource('dlrs', 'DlrsController');

Route::get('docs-list', 'DocumentsController@docs_list');
Route::resource('documents', 'DocumentsController');

Route::get('donation-request-list', 'DonationRequestsController@index');
Route::get('donation-request/all', 'DonationRequestsController@all');
Route::resource('donation-requests', 'DonationRequestsController');

Route::get('email/{brand}/{template}', 'EmailsController@campaign');

Route::get('employees/discount-request', 'EmployeesController@discount_request');
Route::post('employees/discount-request-process', 'EmployeesController@discount_request_process');
Route::resource('employees', 'EmployeesController');

Route::resource('employee-docs', 'EmployeeDocumentsController');
Route::post('employee-docs/{id}', 'EmployeeDocumentsController@store');

Route::resource('event-signups', 'EventSignupsController');

Route::get('events/{id}/delete', 'EventsController@delete');
Route::get('events/clone/{id}', 'EventsController@clone');
Route::get('events/signups/{id}', 'EventsController@view_signups');
Route::get('events/show-all', 'EventsController@show_all');
Route::resource('events', 'EventsController');

Route::get('gallery/imagedelete/{id}', 'GalleryController@imagedelete');
Route::get('gallery/imageedit/{id}', 'GalleryController@imageedit');
Route::get('gallery/show/{id}', 'GalleryController@show');
Route::get('gallery/billboard/{id}', 'GalleryController@billboard')->middleware('cors');
Route::post('gallery/update/{id}', 'GalleryController@update');
Route::post('gallery/imageupdate/{id}', 'GalleryController@imageupdate');
Route::post('gallery/categorystore', 'GalleryController@gallerystore');
Route::post('gallery/imagepost', 'GalleryController@imagepost');
Route::post('gallery/pullgallery', 'GalleryController@pullgallery');
Route::resource('gallery', 'GalleryController');

Route::get('grocery-ads/delete/{id}', 'GroceryAdsController@destroy');
Route::get('grocery-ads/up/{id}', 'GroceryAdsController@up');
Route::get('grocery-ads/down/{id}', 'GroceryAdsController@down');
Route::resource('grocery-ads', 'GroceryAdsController');

Route::get('hbc-ads/delete/{id}', 'HbcAdsController@destroy');
Route::get('hbc-ads/up/{id}', 'HbcAdsController@up');
Route::get('hbc-ads/down/{id}', 'HbcAdsController@down');
Route::resource('hbc-ads', 'HbcAdsController');

Route::get('huddles/summary', 'HuddlesController@summary');
Route::get('huddles/view/{id}', 'HuddlesController@view');
Route::get('huddles/filter/{store}', 'HuddlesController@filter');
Route::post('huddles/store/{id}', 'HuddleCommentsController@store');
Route::resource('huddles', 'HuddlesController');

Route::resource('improvement-requests', 'ImprovementRequestsController');

Route::get('inventory/export/{id}', 'InventoryController@export');
Route::get('inventory-reports', 'InventoryController@list');
Route::get('inventory/pricing-import/{id}', 'InventoryController@pricing_import');
Route::get('inventory-reports/{id}', 'InventoryController@report');
Route::resource('inventory', 'InventoryController');

Route::resource('inventory-item', 'InventoryItemController');
Route::post('inventory-item/store/{id}', 'InventoryItemController@store');

Route::group(['prefix' => 'IT'], function () {
    Route::get('sigis/upload-form', 'IT\SigisController@upload_form');
    Route::post('sigis/upload', 'IT\SigisController@upload');
});

Route::resource('it-assets', 'ItAssetsController');

Route::resource('item', 'ItemController');

Route::resource('item-movement', 'ItemMovementController');

Route::resource('item-occurrence', 'CampaignItemOccurrenceController');

Route::get('kwikee-products/image-display', 'KwikeeProductsController@image_display');
Route::get('kwikee-products/import', 'KwikeeProductsController@form');
Route::post('kwikee-products/import', 'KwikeeProductsController@import');
Route::get('kwikee-products/process/{file}', 'KwikeeProductsController@process');
Route::get('kwikee-products/task', 'KwikeeProductsController@task');

//Route::post('liquor-licenses/store', 'LiquorLicensesController@store');
//Route::get('liquor-licenses/{cashier_number}', 'LiquorLicensesController@create');

Route::get('liquor-licenses/expiring', 'LiquorLicensesController@expiring');
Route::get('liquor-licenses/report', 'LiquorLicensesController@report');
Route::resource('liquor-licenses', 'LiquorLicensesController');
Route::post('liquor-licenses/{id}', 'LiquorLicensesController@store');
//Route::get('expiring', 'LiquorLicensesController@expiring');

//Route::get('liquor-licenses/create', 'LiquorLicensesController@create');

Route::resource('loyalty', 'LoyaltyController');
Route::post('loyalty-register', 'LoyaltyController@register_user');
Route::post('loyalty-login', 'LoyaltyController@validate_user');
Route::get('loyalty-coupons/{brand_id}', 'LoyaltyController@get_coupons');
Route::post('loyalty-clips', 'LoyaltyController@get_user_clips');

Route::get('mailing-lists', 'MailingListsController@index');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;

class Article extends Model
{
    protected $fillable = [
        'title',
        'intro_text',
        'content',
        'cover_image',
        'status',
    ];

    public function getStatusAttribute($value)
    {
        $status = 'Unpublished';

        if ($value == 1) {
            $status = 'Published';
        }

        return $status;
    }

    public function getCoverImgAttribute($value)
    {
        if ($value == '') {
            return URL::to('/img/pending-image.jpg');
        } else {
            return Storage::url('articles/'.$value);
        }
    }

    public function scopeLatest($query)
    {
        return $query
            ->orderBy('created_at', 'desc')
            ->take(2)
            ->get();
    }

    /**
     *   Categories Relationship (Pivot).
     */
    public function categories()
    {
        return $this->belongsToMany(ArticleCategory::class, 'article_article_category');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\ArticleCategory;
use App\ArticlesCategoriesReference;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

class ArticlesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show', 'article']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderBy('created_at', 'desc')->paginate(20);

        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = ArticleCategory::all();

        return view('articles.create', compact($categories));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'       => 'required',
            'intro_text'  => 'required',
            'content'     => 'required',
            'cover_img'   => 'image|max:1000',
            'status'      => 'required|numeric',
        ]);

        $filename = '';

        if ($request->hasFile('cover_img')) {
            $filename = uniqid().'.'.$request->file('cover_img')->getClientOriginalExtension();

            Storage::put('articles/'.$filename, file_get_contents($request->file('cover_img')->getRealPath()), 'public');
        }

        $article = new Article($request->all());

        $article->cover_img = $filename;

        $article->save();

        $article->categories()->attach($request->categories);

        Session::flash('message', [
            'type'    => 'success',
            'message' => 'Article saved successfully',
        ]);

        return redirect()->action('ArticlesController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $id = explode('-', $id)[0];

        $articles = Article::where('status', 1)
            ->orderBy('created_at', 'desc')
            ->get();

        return response($articles, 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id);

        return view('articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title'       => 'required',
            'intro_text'  => 'required',
            'content'     => 'required',
            'cover_img'   => 'mimes:jpg,jpeg,png,gif',
            'status'      => 'required|numeric',
        ]);

        $article = Article::findOrFail($id);

        $filename = basename($article->cover_img);

        $article->fill($request->all());

        if ($request->hasFile('cover_img')) {
            $filename = uniqid().'.'.$request->file('cover_img')->getClientOriginalExtension();

            Storage::put('articles/'.$filename, file_get_contents($request->file('cover_img')->getRealPath()), 'public');
        }

        $article->cover_img = $filename;

        $article->save();

        $article->categories()->sync($request->categories);

        Session::flash('message', [
            'type'    => 'success',
            'message' => 'Article updated successfully',
        ]);

        return redirect()->action('ArticlesController@index');
    }

    /**
     * Confirm deletion for the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $article = Article::findOrFail($id);

        return view('articles.delete', compact('article'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Article::destroy($id);

        Session::flash('message', [
            'type'    => 'success',
            'message' => 'Article deleted successfully',
        ]);

        return redirect('/articles');
    }

    /**
     *  Single Article API.
     */
    public function article($id)
    {
        $article = Article::findOrFail(explode('-', $id)[0]);

        return response($article, 200);
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">Create a new article</div>
                    <div class="panel-body">
                        <form action="{{ action('ArticlesController@store') }}" method="post" enctype="multipart/form-data" >
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="title">Title</label>
                                    <input type="text" class="form-control" name="title" value="{{ old('title') }}" required >
                                </div>
                                <div class="col-md-12 form-group">
                                    <label for="intro_text">Intro Text
                                        <a href="#" data-toggle="tooltip" data-placement="right" title="This is a short overview of the topics you will be covering in the article.">
                                            <i class="fa fa-info-circle"></i>
                                        </a>
                                    </label>
                                    <textarea name="intro_text" id="intro_text" cols="30" rows="10" class="form-control">{{ old('intro_text') }}</textarea>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label for="content">Content
                                        <a href="#" data-toggle="tooltip" data-placement="right" title="This is the body text of the article">
                                            <i class="fa fa-info-circle"></i>
                                        </a>
                                    </label>
                                    <textarea name="content" id="content" cols="30" rows="5" class="form-control summernote">{{ old('content') }}</textarea>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label for="categories">Categories</label>
                                    <select name="categories[]" id="categories" class="form-control multiple-select" multiple="multiple" >
                                        @foreach( \App\ArticleCategory::all() as $category )
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="col-md-6 form-group">
                                    <label for="cover_img">Cover Image</label>
                                    <input type="file" class="form-control" name="cover_img" >
                                    <label>Image size: 500 x 500 px.</label>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="status">Status
                                        <a href="#" data-toggle="tooltip" data-placement="right" title="This will determine if the article is published on the website or not.">
                                            <i class="fa fa-info-circle"></i>
                                        </a>
                                    </label>
                                    <select name="status" id="status" class="form-control">
                                        <option value="">Select...</option>
                                        <option @if(old('status') == 1) selected @endif value="1">Published</option>
                                        <option @if(old('status') == 0) selected @endif value="0">Unpublished</option>
                                    </select>
                                </div>
                                <div class="col-md-12 form-group">
                                    <button class="btn btn-success" type="submit"><i class="fa fa-floppy-o"></i> Save Article</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">Editing: {{ $article->title }}</div>
            <div class="panel-body">
                <form action="{{ action('ArticlesController@update', $article->id) }}" method="post" enctype="multipart/form-data" >
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <div class="row">
                        @if($article->cover_img != "")
                            <div class="col-md-12">
                                <img width="200" src="{{ $article->cover_img }}" alt="{{ $article->title }}" class="img-responsive pull-right">
                            </div>
                        @endif
                        <div class="col-md-12 form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" name="title" value="{{ $article->title }}" required >
                        </div>
                        <div class="col-md-12 form-group">
                            <label for="intro_text">Intro Text</label>
                            <textarea name="intro_text" id="intro_text" cols="30" rows="10" class="form-control">{{ $article->intro_text }}</textarea>
                        </div>
                        <div class="col-md-12 form-group">
                            <label for="content">Content</label>
                            <textarea name="content" id="content" cols="30" rows="5" class="form-control summernote">{{ $article->content }}</textarea>
                        </div>
                        <div class="col-md-12 form-group">
                            <label for="categories">Categories</label>
                            <select name="categories[]" id="categories" class="form-control multiple-select" multiple="multiple" >
                                @foreach( \App\ArticleCategory::all() as $category )
                                    <option @if( in_array($category->id, $article->categories()->select('article_category_id')->pluck('article_category_id')->toArray()) ) ) selected @endif value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="cover_img">Cover Image</label>
                            <input type="file" class="form-control" name="cover_img" >
                            <label>Image size: 500 x 500 px.</label>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="status">Status</label>
                            <select name="status" id="status" class="form-control">
                                <option value="">Select...</option>
                                <option @if($article->status == 'Published') selected @endif value="1">Published</option>
                                <option @if($article->status == 'Unpublished') selected @endif value="0">Unpublished</option>
                            </select>
                        </div>
                        <div class="col-md-12 form-group">
                            <button class="btn btn-success" type="submit"><i class="fa fa-floppy-o"></i> Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">

                <div class="text-right form-group">
                    <a href="{{ action('ArticlesController@create') }}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Create a new article</a>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Articles List</div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Status</th>
                                        <th>Created</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($articles as $article)
                                        <tr>
                                            <td>
                                                <img src="{{ $article->cover_img }}" width="50" alt="{{ $article->title }}">
                                            </td>
                                            <th>
                                                <a href="{{ action('ArticlesController@edit', $article->id) }}">
                                                    {{ $article->title }}
                                                </a>
                                            </th>
                                            <td>{{ $article->status }}</td>
                                            <td>{{ $article->created_at }}</td>
                                            <td class="text-center">
                                                <form action="{{ action('ArticlesController@destroy', $article->id) }}" method="post" onsubmit="return confirm('Are you sure? This can\'t be undone.')">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                    <button class="btn-xs btn-danger">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {{ $articles->render() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">Categories</div>
                    <div class="panel-body">
                        <form action="{{ action('ArticlesCategoriesController@store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="name" required >
                            </div>
                            <button class="btn btn-success btn-block">
                                Save
                            </button>
                        </form>
                        <hr>
                        @foreach( \App\ArticleCategory::orderBy('name')->get() as $category )
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <form action="{{ action('ArticlesCategoriesController@update', $category->id) }}" method="post">
                                        @csrf
                                        {{ method_field('PATCH') }}
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="name" value="{{ $category->name }}" required >
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-success btn-block">
                                                @lang('general.update')
                                            </button>
                                        </div>
                                    </form>
                                    <div class="text-right">
                                        <form action="{{ route('article-category.destroy', $category->id) }}" method="post" onsubmit="return confirm('@lang('general.are-you-sure')')">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-danger">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection