routes/web.php
Route::get('es', function () {
    \Illuminate\Support\Facades\Session::put('language', 'es');

    return back();
});

Route::auth();

Route::get('', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::resource('ad-banners', 'AdBannersController');

Route::resource('adfiles', 'AdfilesController');

Route::resource('adpages', 'AdpagesController');

Route::get('ads/all', 'AdsController@all');
Route::get('ads/banners/{ad}', 'AdsController@banners');
Route::get('ads/subscriber-specials-email/{id}', 'AdsController@email');
Route::get('ads/email/{id}', 'AdsController@ad_email');
Route::get('ads/emailing/{id}', 'AdsController@emailing');
Route::get('ads/text/{id}', 'AdsController@ad_text');
Route::get('ads/current/{brand}', 'AdsController@current');
Route::get('ads/current_api/{brand}', 'AdsController@current_api');
Route::get('ads/duplicate/{id}', 'AdsController@duplicate');
Route::get('ads/generate-pdf/{id}', 'AdsController@generate_pdf');
Route::get('ads/export/{id}', 'AdsController@export');
Route::get('ads/export_csv/{id}', 'AdsController@export_csv');
Route::get('ads/export_csv/{id}', 'AdsController@export_csv');
Route::get('ads/mailing/{id}', 'AdsController@mailing');
Route::get('ads/pages/{brand}', 'AdsController@pages');
Route::get('ads/pdf/{id}', 'AdsController@pdf');
Route::get('ads/pdf-template/{id}', 'AdsController@pdf_template');
Route::get('ads/pdfshift/{id}', 'AdsController@pdfshift');
Route::get('ads/ad/{id}', 'AdsController@ad');
Route::get('generate-pdf/ad/{id}', 'AdsController@ad')->name('generate-pdf');
Route::post('ads/custom-report/{id}', 'AdsController@custom_report');
Route::get('ads/poster/{id}/{page}', 'AdsController@poster');
Route::get('ads/poster-pdf/{id}/{page}', 'AdsController@poster_pdf');
Route::resource('ads', 'AdsController');

Route::get('articles/{id}/delete', 'ArticlesController@delete');
Route::resource('/articles', 'ArticlesController');

Route::resource('article-category', 'ArticlesCategoriesController');

Route::resource('awg-price', 'AwgPriceController');

Route::resource('bab-feedback', 'BABFeedbackController');

Route::get('brand/stores/{id}', 'BrandsController@brand_stores');
Route::get('brand/{id}', 'BrandsController@email');
Route::resource('brands', 'BrandsController');

Route::get('campaigns/orders', 'CampaignsController@orders');
Route::get('campaigns/order-details/{id}', 'CampaignsController@order_details');
Route::get('campaigns/replicate/{id}', 'CampaignsController@replicate');
Route::resource('campaigns', 'CampaignsController');

Route::post('campaign-categories/sort', 'CampaignCategoriesController@sort');
Route::resource('campaign-categories', 'CampaignCategoriesController');

Route::resource('campaign-faqs', 'CampaignFaqsController');

Route::get('campaign-items/duplicate/{id}', 'CampaignItemsController@duplicate');
Route::resource('campaign-items', 'CampaignItemsController');

Route::resource('campaign-item-sizes', 'CampaignItemSizesController');

Route::resource('cashiers', 'CashiersController');

Route::resource('cashiersnumbers', 'CashierNumbersController');
Route::post('cashiersnumbers/{id}', 'CashierNumbersController@store');

Route::resource('categories', 'CategoriesController');

Route::resource('choices', 'ChoicesController');

Route::resource('ctw-area', 'CtwAreaController');

Route::get('ctw-evaluation/heatmap', 'CtwEvaluationController@heatmap')->name('ctw-evaluation.heatmap');
Route::resource('ctw-evaluation', 'CtwEvaluationController');
Route::post('ctw-evaluation/mark-as-completed/{id}', 'CtwEvaluationController@mark_as_completed')->name('ctw-evaluation.mark-as-completed');

Route::resource('ctw-topic', 'CtwTopicController');
Route::post('ctw-topic/store/{id}', 'CtwTopicController@store')->name('ctw-topic.store');

Route::resource('ctw-score', 'CtwScoreController');
Route::get('ctw-score/check/{evaluation}/{topic}', 'CtwScoreController@check');

Route::get('deli-ads/delete/{id}', 'DeliAdsController@destroy');
Route::get('deli-ads/up/{id}', 'DeliAdsController@up');
Route::get('deli-ads/down/{id}', 'DeliAdsController@down');
Route::resource('deli-ads', 'DeliAdsController');

Route::resource('deliMenu', 'DeliMenuController');

Route::resource('deliMenuCategory', 'DeliMenuCategoryController');
Route::get('deliMenuCategory-menu-categories/{menu_id}', 'DeliMenuCategoryController@menu_categories');

Route::resource('deliMenuItem', 'DeliMenuItemController');

Route::resource('departments', 'DepartmentsController');

Route::resource('dlrs', 'DlrsController');

Route::get('docs-list', 'DocumentsController@docs_list');
Route::resource('documents', 'DocumentsController');

Route::get('donation-request-list', 'DonationRequestsController@index');
Route::get('donation-request/all', 'DonationRequestsController@all');
Route::resource('donation-requests', 'DonationRequestsController');

Route::get('email/{brand}/{template}', 'EmailsController@campaign');

Route::get('employees/discount-request', 'EmployeesController@discount_request');
Route::post('employees/discount-request-process', 'EmployeesController@discount_request_process');
Route::resource('employees', 'EmployeesController');

Route::resource('employee-docs', 'EmployeeDocumentsController');
Route::post('employee-docs/{id}', 'EmployeeDocumentsController@store');

Route::resource('event-signups', 'EventSignupsController');

Route::get('events/{id}/delete', 'EventsController@delete');
Route::get('events/clone/{id}', 'EventsController@clone');
Route::get('events/signups/{id}', 'EventsController@view_signups');
Route::get('events/show-all', 'EventsController@show_all');
Route::resource('events', 'EventsController');

Route::get('gallery/imagedelete/{id}', 'GalleryController@imagedelete');
Route::get('gallery/imageedit/{id}', 'GalleryController@imageedit');
Route::get('gallery/show/{id}', 'GalleryController@show');
Route::get('gallery/billboard/{id}', 'GalleryController@billboard')->middleware('cors');
Route::post('gallery/update/{id}', 'GalleryController@update');
Route::post('gallery/imageupdate/{id}', 'GalleryController@imageupdate');
Route::post('gallery/categorystore', 'GalleryController@gallerystore');
Route::post('gallery/imagepost', 'GalleryController@imagepost');
Route::post('gallery/pullgallery', 'GalleryController@pullgallery');
Route::resource('gallery', 'GalleryController');

Route::get('grocery-ads/delete/{id}', 'GroceryAdsController@destroy');
Route::get('grocery-ads/up/{id}', 'GroceryAdsController@up');
Route::get('grocery-ads/down/{id}', 'GroceryAdsController@down');
Route::resource('grocery-ads', 'GroceryAdsController');

Route::get('hbc-ads/delete/{id}', 'HbcAdsController@destroy');
Route::get('hbc-ads/up/{id}', 'HbcAdsController@up');
Route::get('hbc-ads/down/{id}', 'HbcAdsController@down');
Route::resource('hbc-ads', 'HbcAdsController');

Route::get('huddles/summary', 'HuddlesController@summary');
Route::get('huddles/view/{id}', 'HuddlesController@view');
Route::get('huddles/filter/{store}', 'HuddlesController@filter');
Route::post('huddles/store/{id}', 'HuddleCommentsController@store');
Route::resource('huddles', 'HuddlesController');

Route::resource('improvement-requests', 'ImprovementRequestsController');

Route::get('inventory/export/{id}', 'InventoryController@export');
Route::get('inventory-reports', 'InventoryController@list');
Route::get('inventory/pricing-import/{id}', 'InventoryController@pricing_import');
Route::get('inventory-reports/{id}', 'InventoryController@report');
Route::resource('inventory', 'InventoryController');

Route::resource('inventory-item', 'InventoryItemController');
Route::post('inventory-item/store/{id}', 'InventoryItemController@store');

Route::group(['prefix' => 'IT'], function () {
    Route::get('sigis/upload-form', 'IT\SigisController@upload_form');
    Route::post('sigis/upload', 'IT\SigisController@upload');
});

Route::resource('it-assets', 'ItAssetsController');

Route::resource('item', 'ItemController');

Route::resource('item-movement', 'ItemMovementController');

Route::resource('item-occurrence', 'CampaignItemOccurrenceController');

Route::get('kwikee-products/image-display', 'KwikeeProductsController@image_display');
Route::get('kwikee-products/import', 'KwikeeProductsController@form');
Route::post('kwikee-products/import', 'KwikeeProductsController@import');
Route::get('kwikee-products/process/{file}', 'KwikeeProductsController@process');
Route::get('kwikee-products/task', 'KwikeeProductsController@task');

//Route::post('liquor-licenses/store', 'LiquorLicensesController@store');
//Route::get('liquor-licenses/{cashier_number}', 'LiquorLicensesController@create');

Route::get('liquor-licenses/expiring', 'LiquorLicensesController@expiring');
Route::get('liquor-licenses/report', 'LiquorLicensesController@report');
Route::resource('liquor-licenses', 'LiquorLicensesController');
Route::post('liquor-licenses/{id}', 'LiquorLicensesController@store');
//Route::get('expiring', 'LiquorLicensesController@expiring');

//Route::get('liquor-licenses/create', 'LiquorLicensesController@create');

Route::resource('loyalty', 'LoyaltyController');
Route::post('loyalty-register', 'LoyaltyController@register_user');
Route::post('loyalty-login', 'LoyaltyController@validate_user');
Route::get('loyalty-coupons/{brand_id}', 'LoyaltyController@get_coupons');
Route::post('loyalty-clips', 'LoyaltyController@get_user_clips');

Route::get('mailing-lists', 'MailingListsController@index');
Route::post('mailing-lists/store', 'MailingListsController@store');

Route::get('meat-ads/delete/{id}', 'MeatAdsController@destroy');
Route::get('meat-ads/up/{id}', 'MeatAdsController@up');
Route::get('meat-ads/down/{id}', 'MeatAdsController@down');
Route::resource('meat-ads', 'MeatAdsController');

Route::get('new-items/show/{id}', 'NewItemsController@show');
Route::resource('new-items', 'NewItemsController');

Route::get('newsletter-images/delete/{id}', 'NewsletterImageController@destroy');
Route::get('newsletters/show/{id}', 'NewsletterController@show');

app/CtwEvaluation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CtwEvaluation extends Model
{
    protected $fillable = ['store_id', 'comments'];

    /**
     *  User ID Default Value.
     */
    public function __construct(array $attributes = [])
    {
        $this->user_id = auth()->user()->id;

        parent::__construct($attributes);
    }

    /**
     *  Scores Relationship.
     */
    public function scores()
    {
        return $this->hasMany(CtwScore::class, 'evaluation_id');
    }

    /**
     *  Store Relationship.
     */
    public function store()
    {
        return $this->belongsTo(Store::class);
    }

    /**
     *  User Relationship.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CtwEvaluationController.php
<?php

namespace App\Http\Controllers;

use App\CtwArea;
use App\CtwEvaluation;
use App\CtwScore;
use App\Store;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Lang;

class CtwEvaluationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $evaluations = CtwEvaluation::paginate(10);

        return view('ctw-evaluation.index', compact('evaluations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ctw-evaluation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'store_id' => 'required|integer',
        ]);

        $evaluation = new CtwEvaluation(request()->all());

        $evaluation->save();

        return redirect()
            ->route('ctw-evaluation.edit', $evaluation->id)
            ->with(['message' => [
                'type'    => 'success',
                'message' => Lang::get('ctw-evaluation.title').': '.Lang::get('general.saved'),
            ]]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CtwEvaluation  $ctwEvaluation
     * @return \Illuminate\Http\Response
     */
    public function show(CtwEvaluation $ctwEvaluation)
    {
        $evaluation = $ctwEvaluation;

        return view('ctw-evaluation.show', compact('evaluation'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CtwEvaluation  $ctwEvaluation
     * @return \Illuminate\Http\Response
     */
    public function edit(CtwEvaluation $ctwEvaluation)
    {
        $evaluation = $ctwEvaluation;

        return view('ctw-evaluation.edit', compact('evaluation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CtwEvaluation  $ctwEvaluation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CtwEvaluation $ctwEvaluation)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CtwEvaluation  $ctwEvaluation
     * @return \Illuminate\Http\Response
     */
    public function destroy(CtwEvaluation $ctwEvaluation)
    {
        //
    }

    /**
     *  Mark As Completed.
     */
    public function mark_as_completed($id)
    {
        $evaluation = CtwEvaluation::find($id);

        if ($evaluation->scores->count() == 0) {
            return back()
                ->with([
                    'message' => [
                        'type' => 'danger',
                        'message' => Lang::get('ctw-evaluation.evaluation-has-no-scores'),
                    ],
                ]);
        }

        $evaluation->status = 1;

        $evaluation->save();

        return redirect()
            ->route('ctw-evaluation.show', $evaluation->id)
            ->with(['message' => [
                'type'    => 'success',
                'message' => Lang::get('ctw-evaluation.evaluation-has-been-marked-as-completed'),
            ]]);
    }

    /**
     *  Heatmap.
     */
    public function heatmap()
    {
        $areas = CtwArea::orderBy('name')->get();

        $stores = Store::active()->get();

        $scores = DB::table('ctw_scores')
            ->join('ctw_topics', 'ctw_scores.topic_id', '=', 'ctw_topics.id')
            ->join('ctw_evaluations', 'ctw_evaluations.id', '=', 'ctw_scores.evaluation_id')
            ->join('ctw_areas', 'ctw_topics.ctw_area_id', '=', 'ctw_areas.id')
            ->join('stores', 'ctw_evaluations.store_id', '=', 'stores.id')
            ->select(
                DB::raw('ctw_scores.id as score_id'),
                DB::raw('stores.store_code as store'),
                DB::raw('ctw_evaluations.id as evaluation'),
                DB::raw('ctw_areas.id as area'),
                DB::raw('ctw_areas.name as area_name'),
                DB::raw('ctw_topics.id as topic'),
                DB::raw('ctw_topics.topic as topic_name'),
                'score'
            )
            ->orderBy('ctw_evaluations.created_at', 'DESC')
            ->get();

//        return $scores;

        return view('ctw-evaluation.heatmap', compact('areas', 'stores', 'scores'));
    }
}

resources/views/ctw-evaluation/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <p class="lead text-center">
                    @lang('ctw-evaluation.start')
                </p>
                <form action="{{ route('ctw-evaluation.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="store_id">@lang('ctw-evaluation.store')</label>
                        <select name="store_id" id="store_id" class="form-control">
                            <option value="">@lang('general.select')...</option>
                            @foreach(\App\Store::active()->orderBy('store_code')->get() as $store)
                                <option @if( old('comments') == $store->id ) selected @endif value="{{ $store->id }}">{{ $store->store_code }} - {{ $store->brands->name }} {{ $store->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="comments">@lang('ctw-evaluation.comments')</label>
                        <textarea name="comments" id="comments" cols="30" rows="10" class="form-control">{{ old('comments') }}</textarea>
                    </div>
                    <button class="btn btn-success btn-block">
                        @lang('general.start')
                    </button>
                </form>
            </div>
        </div>
    </div>

    @endsection

resources/views/ctw-evaluation/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <p class="lead text-center">
            Commitment To Win<br />
            {{ $evaluation->store->store_code }} {{ $evaluation->store->brands->name }} {{ $evaluation->store->name }}
        </p>
        <p class="text-center">
            @lang('ctw-evaluation.started'): {{ $evaluation->created_at }}
        </p>

        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                @foreach( \App\CtwArea::whereHas('brands', function($q) use ($evaluation){ return $q->where('brands.id', $evaluation->store->brands->id); })->orderBy('name')->get() as $area )
                    <div class="panel panel-default">
                        <div class="panel-heading text-center">
                            {{ $area->name }}
                        </div>
                        <div class="panel-body">
                            @foreach($area->topics as $topic)
                            <rating-component :topic="'{{ $topic }}'" :evaluation="'{{ $evaluation->id }}'"></rating-component>
                            @endforeach
                        </div>
                    </div>
                @endforeach

                <form action="{{ route('ctw-evaluation.mark-as-completed', $evaluation->id) }}" method="post">
                    @csrf
                    <button class="btn btn-success btn-block">
                        @lang('ctw-evaluation.mark-as-completed')
                    </button>
                </form>
            </div>
        </div>

    </div>

    @endsection

resources/views/ctw-evaluation/heatmap.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <p class="lead text-center">
            Commitment To Win (CTW)<br />
            Heatmap
        </p>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="text-center">Store / Area</th>
                    @foreach( $areas as $area )
                    <th class="text-center">
                        {{ $area->name }}
                    </th>
                    @endforeach
                </tr>
                </thead>
                <tbody>
                @foreach($stores as $store)
                <tr>
                    <th class="text-center">{{ $store->store_code }}</th>
                    @php $i = 0 @endphp
                    @foreach($areas as $area)
                    <td class="text-center {{ $scores->where('area', $area->id)->where('store', $store->store_code)->avg('score') > 1 ? 'success' : ($scores->where('area', $area->id)->where('store', $store->store_code)->avg('score') < .5 ? 'danger' : 'warning') }}">
                        @if( $scores->where('area', $area->id)->where('store', $store->store_code)->first() ) <a href="#" data-toggle="modal" data-target="#modal-scores-{{ $i }}"> @endif
                        {{ number_format($scores->where('area', $area->id)->where('store', $store->store_code)->avg('score'), 2) }}
                        @if( $scores->where('area', $area->id)->where('store', $store->store_code)->first() ) </a> @endif
                        <!-- Modal -->
                        <div class="modal fade" id="modal-scores-{{ $i }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">{{ $area->name }}</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="table-responsive">
                                            <table class="table">
                                                @foreach($scores->where('area', $area->id) as $s)
                                                @php $scales = [0=>'Needs Improvement', 1=>'Near Model', 2=>'Model'] @endphp
                                                @php $styles = [0=>'danger', 1=>'warning', 2=>'success']; @endphp
                                                <tr class="{{ $styles[$s->score] }}">
                                                    <td class="text-left">{{ $s->topic_name }}</td>
                                                    <td class="text-center">
                                                        {{ $scales[$s->score] }}
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </table>
                                        </div>
                                        <p class="text-center">
                                            <b>{{ $area->name }} score: {{ number_format($scores->where('area', $area->id)->avg('score'),2) }}</b>
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    @php $i++ @endphp
                    @endforeach
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    @endsection

resources/views/ctw-evaluation/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <p class="lead">@lang('ctw-evaluation.title')</p>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>@lang('ctw-evaluation.store')</th>
                    <th>@lang('ctw-evaluation.user')</th>
                    <th>@lang('ctw-evaluation.created')</th>
                    <th>@lang('ctw-evaluation.status')</th>
                </tr>
                </thead>
                <tbody>
                @foreach($evaluations as $evaluation)
                <tr>
                    <td>{{ $evaluation->store->store_code }} {{ $evaluation->store->brands->name }} {{ $evaluation->store->name }}</td>
                    <td>{{ $evaluation->user->name }}</td>
                    <td>{{ $evaluation->created_at }}</td>
                    <td>
                        @if($evaluation->status == 1)
                            <a href="{{ route('ctw-evaluation.show', $evaluation->id) }}">
                                @lang('ctw-evaluation.show-results')
                            </a>
                        @else
                            <a href="{{ route('ctw-evaluation.edit', $evaluation->id) }}">
                                @lang('ctw-evaluation.continue')
                            </a>
                        @endif
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
            {{ $evaluations->render() }}
        </div>
    </div>

    @endsection

resources/views/ctw-evaluation/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <p class="lead text-center">
            Commitment To Win Evaluation<br />
            {{ $evaluation->store->brands->name }} - {{ $evaluation->store->name }} ({{ $evaluation->store->store_code }})
        </p>
        @foreach(\App\CtwArea::whereHas('brands', function($q) use ($evaluation){ return $q->where('brands.id', $evaluation->store->brands->id);; })->orderBy('name')->get() as $area)
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th class="text-center">{{ $area->name }}</th>
                    <th class="text-center">@lang('ctw-evaluation.score')</th>
                </tr>
                </thead>
                <tbody>
                @php $topics = []; @endphp
                @foreach($area->topics as $topic)
                @if( $evaluation->scores->where('topic_id', $topic->id)->first() )
                <tr class="{{ $evaluation->scores->where('topic_id', $topic->id)->first()->score_class }}">
                    <td><b>{{ $topic->topic }}</b> @if( $evaluation->scores->where('topic_id', $topic->id)->first()->comments != null ) <br /><i>{{ $evaluation->scores->where('topic_id', $topic->id)->first()->comments }}</i> @endif</td>
                    <td width="30%" class="text-right">
                        {{ $evaluation->scores->where('topic_id', $topic->id)->first()->score_label }}
                    </td>
                </tr>
                @endif
                @php array_push($topics, $topic->id) @endphp
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <td>@lang('ctw-evaluation.score')</td>
                    <td class="text-right">
                        {{ number_format($evaluation->scores->whereIn('topic_id', $topics)->avg('score'), 2) }}
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
        @endforeach
        <p class="lead text-right">Global Score: {{ number_format($evaluation->scores->avg('score'), 2) }}</p>
    </div>

    @endsection